# -*- coding: utf-8 -*-
"""Json_to_xml_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMg4Gx0TMiqmCUoVqEMNTepiViBGczY3
"""

import json
import xml.etree.ElementTree as ET

def json_to_xml(json_data):
    root = ET.Element("people")

    for person in json_data:
        person_elem = ET.SubElement(root, "person")

        for key, value in person.items():
            child = ET.SubElement(person_elem, key)
            child.text = str(value)

    return ET.tostring(root, encoding='utf-8', method='xml').decode('utf-8')

# Чтение данных из файла JSON
with open('Data.json', 'r', encoding='utf-8') as json_file:
    Data = json.load(json_file)

# Конвертация в XML
xml_data = json_to_xml(Data)

# Запись данных в файл XML
with open('Data.xml', 'w', encoding='utf-8') as xml_file:
    xml_file.write(xml_data)

print("Конвертация завершена. Данные сохранены в Data.xml.")